# Generated by Django 6.0.2 on 2026-02-13 06:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputeTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(help_text='Identifier of the requesting device', max_length=255)),
                ('task_type', models.CharField(choices=[('COMPOSITE', 'Composite'), ('COMPLEX', 'Complex')], max_length=20)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='RECEIVED', max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_time_ms', models.FloatField(blank=True, help_text='Processing duration in milliseconds', null=True)),
                ('firebase_result_path', models.CharField(blank=True, default='', help_text='Firestore/Storage path where result was saved', max_length=512)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='ComputeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.computetask')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
